In [2]:
#Cody Pace
#WGU D598 Task 2
#August 2025

#Import libraries
import pandas as pd
from IPython.display import display

#Import the Excel file as a data frame
df_input = pd.read_excel("D598 Data Set.xlsx")

#Identify duplicate records, provide count, Business ID for later triage, then remove the duplicates
df_duplicates = df_input[df_input.duplicated()]
duplicates_count = len(df_duplicates)
print(f'Number of duplicate records: {duplicates_count}')

#Provide the Business ID for the duplicate record for easy review.
if len(df_duplicates) > 0:
    print(df_duplicates[['Business ID']])
    df_input = df_input.drop_duplicates()
    print(f'{duplicates_count} duplicate records removed\n')
else:
    print('No duplicates were found in the file.\n')

#Group all rows by Business State
df_state_cols = [ 'Total Long-term Debt', 'Total Equity', 'Debt to Equity', 
                 'Total Liabilities', 'Total Revenue', 'Profit Margin']
df_state_stats = df_input.groupby('Business State')

#Descriptive statistics (mean, median, min, and max)
#for Total Long-term Debt, Total Equity, Debt to Equity,
#Total Liabilities, Total Revenue, Profit Margin
desc_stats = ['mean', 'median', 'min', 'max']
df_desc_stats = df_state_stats[df_state_cols].agg(desc_stats)
df_desc_stats.columns = ['_'.join([col, stat]) for col, stat in df_desc_stats.columns]
print('Descriptive Statistics by State:')
display(df_desc_stats)

#Filter df_desc_stats to identify all businesses with debt-to-equity (dbteq) ratios that are negative
df_negative_dbteq = df_input[df_input['Debt to Equity'] < 0].sort_values(by = 'Debt to Equity')
print('Businesses With A Negative Debt To Equity Ratio')
df_negative_dbteq.reset_index(drop=True, inplace=True)
display(df_negative_dbteq[['Business ID', 'Business State', 'Debt to Equity']])
print(f'There are {len(df_negative_dbteq)} businesses with a negative Debt to Equity Ratio\n')

#Find the Debt-to-income ratio for every business and store in a new data frame.
#Debt-to-income ratio = long-term debt / revenue

#Find businesses with a Total Revenue = $0
df_zero_revenue = df_input[df_input['Total Revenue'] == 0]

#Warn the user if records are found with $0 Total Revenue. Provide Business ID for triage.
if not df_zero_revenue.empty:
    print('WARNING: The following businesses have a Total Revenue = $0 and will be skipped:')
    display(df_zero_revenue[['Business ID']])

#Filter records out
df_filtered_rev = df_input[df_input['Total Revenue'] != 0]
df_input = df_filtered_rev.copy()

#Calculate Debt-to-Income Ratio
df_debt_income_ratio = df_filtered_rev[['Business ID', 'Total Long-term Debt', 'Total Revenue']].copy()
df_debt_income_ratio['Debt-to-Income Ratio'] = df_debt_income_ratio['Total Long-term Debt'] / df_debt_income_ratio['Total Revenue']
df_debt_income_ratio = df_debt_income_ratio.sort_values(by = 'Debt-to-Income Ratio', ascending=False)
print('Debt-to-income ratio for each business')
df_debt_income_ratio.reset_index(drop=True, inplace=True)
display(df_debt_income_ratio)

#Concatenate the debt-to-income ratio data frame with the original data frame
df_final = pd.merge(df_input, df_debt_income_ratio[['Business ID', 'Debt-to-Income Ratio']], on='Business ID', how='left')
print('Final Output')
df_final.reset_index(drop=True, inplace=True)
display(df_final)

Number of duplicate records: 0
No duplicates were found in the file.

Descriptive Statistics by State:

,Total Long-term Debt_mean,Total Long-term Debt_median,Total Long-term Debt_min,Total Long-term Debt_max,Total Equity_mean,Total Equity_median,Total Equity_min,Total Equity_max,Debt to Equity_mean,Debt to Equity_median,...,Total Liabilities_min,Total Liabilities_max,Total Revenue_mean,Total Revenue_median,Total Revenue_min,Total Revenue_max,Profit Margin_mean,Profit Margin_median,Profit Margin_min,Profit Margin_max
Business State,,,,,,,,,,,,,,,,,,,,,
Alabama,6.743890e+08,6.743890e+08,5.314000e+06,1.343464e+09,1.441039e+09,1.441039e+09,2.405848e+07,2.858019e+09,0.345473,0.345473,...,2.369800e+07,3.764193e+09,6.968309e+08,6.968309e+08,137344716,1256317000,0.403732,0.403732,0.297094,0.510371
Arizona,6.508800e+07,6.508800e+07,6.508800e+07,6.508800e+07,5.915300e+07,5.915300e+07,5.915300e+07,5.915300e+07,1.100333,1.100333,...,1.109380e+08,1.109380e+08,2.155800e+08,2.155800e+08,215580000,215580000,0.206902,0.206902,0.206902,0.206902
Arkansas,8.960450e+07,8.960450e+07,7.036600e+07,1.088430e+08,1.082420e+08,1.082420e+08,1.005380e+08,1.159460e+08,0.844746,0.844746,...,2.133560e+08,2.144080e+08,4.789090e+08,4.789090e+08,402813000,555005000,0.098319,0.098319,0.073156,0.123482
California,3.273964e+07,4.721500e+06,1.500000e+04,3.349970e+08,4.535982e+07,1.427150e+07,-1.569100e+07,3.211750e+08,0.169920,0.154170,...,2.658000e+06,7.888110e+08,8.869559e+07,3.753150e+07,1100539,276869000,0.287947,0.301992,-0.084923,0.505955
Colorado,8.470025e+07,2.932700e+07,3.375000e+06,3.753220e+08,2.007589e+08,6.077850e+07,1.284525e+07,9.339710e+08,0.619971,0.874711,...,6.787000e+06,5.822750e+08,2.486542e+08,2.023990e+08,7616000,696473000,0.346033,0.314631,0.124017,0.655796
Connecticut,1.851200e+07,1.851200e+07,1.851200e+07,1.851200e+07,4.399091e+06,4.399091e+06,4.399091e+06,4.399091e+06,4.208142,4.208142,...,3.387400e+07,3.387400e+07,7.098051e+07,7.098051e+07,70980512,70980512,0.559851,0.559851,0.559851,0.559851
Delaware,6.156325e+07,6.016500e+07,8.331000e+06,1.175920e+08,1.514428e+08,1.393095e+08,4.837900e+07,2.787730e+08,0.411822,0.364076,...,3.976500e+07,5.587490e+08,2.789488e+08,2.566895e+08,46180000,556236000,0.213083,0.231342,-0.020394,0.410044
Florida,1.230350e+07,1.809000e+06,3.000000e+03,4.559300e+07,5.475486e+07,1.188788e+07,2.597665e+06,1.926460e+08,0.315141,0.148805,...,2.947000e+06,9.444700e+07,2.664470e+07,3.017874e+07,11783539,34437774,-0.438503,0.295580,-2.850582,0.505412
Hawaii,6.055000e+08,6.055000e+08,6.055000e+08,6.055000e+08,1.173200e+09,1.173200e+09,1.173200e+09,1.173200e+09,0.516110,0.516110,...,1.110400e+09,1.110400e+09,3.652000e+08,3.652000e+08,365200000,365200000,0.348850,0.348850,0.348850,0.348850
Idaho,2.463500e+06,2.463500e+06,1.600000e+04,4.911000e+06,2.155825e+08,2.155825e+08,4.846014e+06,4.263190e+08,0.506724,0.506724,...,7.162000e+06,3.762360e+08,1.177167e+09,1.177167e+09,6849150,2347485000,0.282456,0.282456,0.129654,0.435258
Illinois,1.132533e+07,9.029000e+06,1.598000e+06,3.366500e+07,6.759322e+07,4.750640e+07,1.276350e+07,2.153040e+08,0.235302,0.155731,...,1.014700e+07,1.594400e+08,2.178647e+08,1.095325e+08,28227000,734334000,0.138131,0.222600,-0.716619,0.631997
Indiana,2.168600e+07,5.112000e+06,4.946000e+06,5.500000e+07,5.990800e+07,8.231000e+07,9.459000e+06,8.795500e+07,0.421626,0.540438,...,1.613800e+07,9.187700e+07,2.499967e+08,1.329910e+08,22068000,594931000,0.241067,0.164515,0.161278,0.397408
Iowa,6.252000e+06,6.252000e+06,6.252000e+06,6.252000e+06,1.829362e+07,1.829362e+07,1.829362e+07,1.829362e+07,0.341758,0.341758,...,1.447400e+07,1.447400e+07,3.422655e+07,3.422655e+07,34226553,34226553,0.265015,0.265015,0.265015,0.265015
Kentucky,1.688900e+07,1.688900e+07,1.688900e+07,1.688900e+07,1.804600e+07,1.804600e+07,1.804600e+07,1.804600e+07,0.935886,0.935886,...,2.598600e+07,2.598600e+07,1.367530e+08,1.367530e+08,136753000,136753000,0.023663,0.023663,0.023663,0.023663
Louisiana,3.790000e+08,3.790000e+08,3.790000e+08,3.790000e+08,5.599650e+08,5.599650e+08,5.599650e+08,5.599650e+08,0.676828,0.676828,...,6.133580e+08,6.133580e+08,8.565000e+08,8.565000e+08,856500000,856500000,0.212855,0.212855,0.212855,0.212855
MInnesota,7.493429e+07,1.016900e+07,1.332000e+06,3.895890e+08,1.005679e+08,1.824600e+07,1.213765e+07,5.348300e+08,0.598212,0.577140,...,3.629000e+06,1.061189e+09,1.914527e+08,1.278780e+08,15104422,743414000,0.333169,0.262657,0.009197,0.762859
Maine,8.960000e+05,8.960000e+05,8.960000e+05,8.960000e+05,9.395714e+06,9.395714e+06,9.395714e+06,9.395714e+06,0.095363,0.095363,...,1.565000e+06,1.565000e+06,6.007176e+06,6.007176e+06,6007176,6007176,0.578504,0.578504,0.578504,0.578504
Maryland,1.448550e+07,9.585000e+05,2.500000e+04,5.600000e+07,1.010719e+08,5.399145e+07,1.497359e+07,2.813310e+08,0.080409,0.060828,...,7.530000e+05,1.476180e+08,8.661347e+07,1.984594e+07,8030016,298732000,0.184145,0.237873,-0.092398,0.353230
Massachusetts,7.717600e+06,4.911000e+06,2.320000e+05,2.458300e+07,3.730778e+07,1.064600e+07,6.346284e+06,1.460440e+08,0.328288,0.239401,...,1.000700e+07,7.095000e+07,9.221797e+07,4.275300e+07,21341052,270950000,0.353531,0.385057,0.209786,0.460365
Michigan,3.611400e+07,2.160900e+07,2.033000e+06,8.470000e+07,2.356307e+08,4.272300e+07,1.443500e+07,6.497340e+08,0.258997,0.140838,...,7.781000e+06,2.672530e+08,8.521257e+08,6.228000e+07,23649000,2470448000,0.439004,0.406402,0.127149,0.783462
Missouri,1.730845e+08,1.730845e+08,6.080000e+07,2.853690e+08,8.377200e+07,8.377200e+07,2.340000e+07,1.441440e+08,2.289020,2.289020,...,1.281000e+08,3.359070e+08,4.870285e+08,4.870285e+08,412557000,561500000,0.226158,0.226158,0.202850,0.249466
Montana,8.730500e+06,8.730500e+06,1.002000e+06,1.645900e+07,3.579810e+06,3.579810e+06,-3.842372e+06,1.100199e+07,-2.096239,-2.096239,...,3.889000e+06,3.272000e+07,2.204712e+07,2.204712e+07,11020829,33073414,0.321021,0.321021,0.059599,0.582444
Nebraska,1.891900e+07,1.891900e+07,1.891900e+07,1.891900e+07,5.564090e+07,5.564090e+07,5.564090e+07,5.564090e+07,0.340020,0.340020,...,5.073400e+07,5.073400e+07,1.211053e+09,1.211053e+09,1211052634,1211052634,0.382938,0.382938,0.382938,0.382938
Nevada,5.232000e+06,5.232000e+06,5.232000e+06,5.232000e+06,2.024400e+07,2.024400e+07,2.024400e+07,2.024400e+07,0.258447,0.258447,...,2.375600e+07,2.375600e+07,2.482659e+07,2.482659e+07,24826587,24826587,0.081992,0.081992,0.081992,0.081992
New Jersey,1.083810e+08,5.549000e+06,3.000000e+04,7.010560e+08,1.271195e+08,2.392687e+07,2.696434e+06,8.270000e+08,0.558806,0.338884,...,7.613000e+06,2.097855e+09,1.927066e+08,5.849458e+07,7827258,731421000,0.230617,0.237778,0.045307,0.381234
New Mexico,1.670420e+09,1.670420e+09,1.670420e+09,1.670420e+09,1.762127e+09,1.762127e+09,1.762127e+09,1.762127e+09,0.947957,0.947957,...,3.738083e+09,3.738083e+09,1.387923e+09,1.387923e+09,1387923000,1387923000,0.326908,0.326908,0.326908,0.326908
New York,3.356664e+07,6.451500e+06,1.870000e+05,1.904540e+08,6.566206e+07,3.536200e+07,-1.303788e+07,3.929430e+08,0.449751,0.215768,...,1.743000e+06,3.464900e+08,1.439868e+08,7.015900e+07,2389053,731997000,0.315717,0.316376,0.084509,0.489443
North Carolina,1.949496e+08,2.265400e+07,1.600000e+04,7.301570e+08,1.807661e+08,3.155600e+07,5.562054e+06,6.136390e+08,0.581290,0.717898,...,2.426000e+06,2.437531e+09,1.972347e+09,9.120900e+07,419322,8843168000,0.223596,0.205343,0.037283,0.477728
Ohio,1.151766e+08,1.193840e+08,2.429000e+06,2.638800e+08,7.776800e+07,6.744800e+07,-1.112970e+08,2.986160e+08,0.114115,0.623473,...,9.884000e+06,5.921740e+08,5.673696e+08,7.001860e+08,9423000,1263331000,0.025611,0.196753,-0.729173,0.320697
Oregon,8.280500e+06,8.280500e+06,5.511000e+06,1.105000e+07,6.504541e+07,6.504541e+07,1.885881e+07,1.112320e+08,0.195783,0.195783,...,1.014600e+07,5.905400e+07,9.622596e+07,9.622596e+07,13271914,179180000,0.480619,0.480619,0.326069,0.635169
Pennsylvania,8.821533e+07,8.679600e+07,2.970000e+05,1.775530e+08,7.364100e+07,1.300600e+07,1.145900e+07,1.964580e+08,5.319758,0.441804,...,2.425700e+07,2.590890e+08,2.276010e+08,1.807680e+08,30102000,471933000,0.295548,0.179172,0.154784,0.552688
Rhode Island,5.104500e+07,5.104500e+07,5.104500e+07,5.104500e+07,2.749000e+07,2.749000e+07,2.749000e+07,2.749000e+07,1.856857,1.856857,...,8.787700e+07,8.787700e+07,2.081730e+08,2.081730e+08,208173000,208173000,0.312274,0.312274,0.312274,0.312274
South Carolina,1.303430e+08,1.303430e+08,9.476300e+07,1.659230e+08,7.474850e+07,7.474850e+07,8.431000e+06,1.410660e+08,10.175936,10.175936,...,1.708440e+08,2.873460e+08,4.765580e+08,4.765580e+08,462593000,490523000,0.260323,0.260323,0.239587,0.281059
Tennessee,6.562650e+07,6.562650e+07,2.949400e+07,1.017590e+08,1.117655e+08,1.117655e+08,7.077100e+07,1.527600e+08,0.815469,0.815469,...,1.096420e+08,1.780950e+08,3.587900e+08,3.587900e+08,344374000,373206000,0.250241,0.250241,0.209187,0.291294
Texas,5.424593e+08,1.920000e+07,9.310000e+05,3.183823e+09,4.354187e+08,1.559730e+08,6.069000e+06,2.414452e+09,0.629349,0.397251,...,6.466000e+06,4.884634e+09,4.300853e+08,3.006070e+08,15588000,1832253000,0.261672,0.287587,-0.394277,0.689392
Utah,1.786000e+06,1.786000e+06,1.562000e+06,2.010000e+06,1.303053e+06,1.303053e+06,-3.602481e+06,6.208587e+06,-0.153181,-0.153181,...,6.302000e+06,8.896000e+06,2.364783e+07,2.364783e+07,17757388,29538275,0.562066,0.562066,0.391569,0.732562
Virginia,2.682600e+07,1.300000e+07,2.100000e+04,9.020800e+07,7.573291e+07,4.950270e+07,6.700572e+06,1.868030e+08,0.256774,0.262612,...,4.138000e+06,1.937260e+08,1.614041e+08,7.526604e+07,159583,471638000,-24.301115,0.141573,-122.221145,0.370593
Washington,5.242200e+07,5.242200e+07,1.060300e+07,9.424100e+07,1.242892e+08,1.242892e+08,-1.327166e+07,2.618500e+08,-0.219508,-0.219508,...,1.662500e+07,1.716090e+08,1.841972e+08,1.841972e+08,8949401,359445000,0.154017,0.154017,-0.140085,0.448119
Washington D.C.,5.240670e+08,5.240670e+08,5.240670e+08,5.240670e+08,1.302718e+09,1.302718e+09,1.302718e+09,1.302718e+09,0.402287,0.402287,...,2.957342e+09,2.957342e+09,2.466138e+09,2.466138e+09,2466138000,2466138000,0.108641,0.108641,0.108641,0.108641
Wisconsin,3.958340e+07,2.396000e+06,2.030000e+05,1.908170e+08,6.295184e+07,1.604900e+07,6.126073e+06,2.500870e+08,0.289946,0.262882,...,6.997000e+06,3.459310e+08,1.124273e+08,3.010200e+07,7723699,397267000,0.483302,0.505813,0.122358,0.837386

Businesses With A Negative Debt To Equity Ratio

   Business ID Business State  Debt to Equity
0  14535932013        Montana       -4.283552
1    934562013           Ohio       -2.370953
2   9323722013     California       -1.374036
3   8343652013     Washington       -0.798921
4  10919832013           Utah       -0.557949
5  11245242013     California       -0.269484
6  14639722013       New York       -0.014343

There are 7 businesses with a negative Debt to Equity Ratio

Debt-to-income ratio for each business

     Business ID  Total Long-term Debt  Total Revenue  Debt-to-Income Ratio
0    13752052013          3.400000e+07        7616000              4.464286
1    12826482013          3.183823e+09      999506000              3.185397
2     3518172013          1.142368e+09      584401000              1.954767
3     3158522013          3.140516e+09     1832253000              1.714019
4    15456542013          6.055000e+08      365200000              1.657996
..           ...                   ...            ...                   ...
145   1021092013          2.500000e+04       15383877              0.001625
146   7889202013          1.500000e+04       12249000              0.001225
147   7214472013          3.000000e+04       28827163              0.001041
148   8899712013          3.000000e+03       11783539              0.000255
149  13239742013          1.600000e+04     2347485000              0.000007

[150 rows x 4 columns]

Final Output

,Business ID,Business State,Total Long-term Debt,Total Equity,Debt to Equity,Total Liabilities,Total Revenue,Profit Margin,Debt-to-Income Ratio
0,41872013,Kentucky,16889000.0,1.804600e+07,0.935886,2.598600e+07,136753000,0.023663,0.123500
1,76232013,Iowa,6252000.0,1.829362e+07,0.341758,1.447400e+07,34226553,0.265015,0.182665
2,160992013,Texas,19200000.0,1.778580e+08,0.107951,7.278700e+07,384196000,0.130413,0.049974
3,197452013,Delaware,117592000.0,2.787730e+08,0.421820,5.587490e+08,444306000,0.196768,0.264664
4,241042013,Illinois,4408000.0,5.206400e+07,0.084665,1.989800e+07,121541000,0.168305,0.036268
...,...,...,...,...,...,...,...,...,...
145,14733342013,California,6602000.0,3.872871e+07,0.170468,2.183800e+07,78356493,0.213007,0.084256
146,14871012013,Maryland,56000000.0,2.813310e+08,0.199054,1.476180e+08,298732000,0.353230,0.187459
147,14889172013,MInnesota,1332000.0,1.392683e+07,0.095643,3.629000e+06,15104422,0.727563,0.088186
148,15456542013,Hawaii,605500000.0,1.173200e+09,0.516110,1.110400e+09,365200000,0.348850,1.657996
149,15528002013,MInnesota,92807000.0,7.873600e+07,1.178711,1.629060e+08,229564000,0.762859,0.404275